s3:
 key: ''
 secret: ''
 bucket: ''
 region: ''
 endpoint: ''

tmp: '/tmp'
schedule:

sites:
    one:
        destination: '/one'
        assets:
           db: '.env'
           files:
               - '/home/www/site/example.com/storage/app'
    two:
        destination: '/two'
        assets:
          db: '.env'
          files:
              - '/home/www/site/example.org/storage/app'

